version: "3.9"
services:
  desertsend-db:
    image: mysql:8.0
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--sql_mode=NO_ENGINE_SUBSTITUTION",
      ]
    volumes:
      - desertsend-db-data:/var/lib/mysql:rw
      - ../de-services/updates/2023:/docker-entrypoint-initdb.d
      - ../de-services/dev-data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password" # ${DB_PASSWORD}
      MYSQL_DATABASE: volunteers_db
    networks:
      default:
        aliases:
          - desertsend_db

volumes:
  desertsend-db-data:
    driver_opts:
      type: none
      device: ${HOME}/docker/volumes/desertsend-db-data
      o: bind


