version: "3.9"
services:
  desertsend-db:
    image: mysql:8.0
    command: >
      --lower_case_table_names=1 
      --default-authentication-plugin=mysql_native_password
      --sql_mode=NO_ENGINE_SUBSTITUTION
    volumes:
      - ./updates/2023:/docker-entrypoint-initdb.d

    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password" # ${DB_PASSWORD}
      MYSQL_DATABASE: volunteers_db
    networks:
      default:
        aliases:
          - desertsend_db
volumes:
  desertsend-db-data:
    driver_opts:
      type: none
      device: ${HOME}/docker/volumes/desertsend-db-data
      o: bind
