name: deserts-end-api Continuous Integration

on:
  push:
    branches: [CI-CD]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      API_KEY: ${{ secrets.MY_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm version
        run: |
          npm --version

      - name: node version
        run: |
          node --version

      - name: npm install
        run: |
          npm install

      - name: npm test
        run: |
          npm run test

      - name: npm run build
        run: |
          npm run build
