name: Integration Tests with MySQL

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [develop]

env:
  aws-region: ${{ secrets.AWS_REGION }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: # Use the AWS credentials from the AWS CodeArtifact domain
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull DB image from ECR
        run: docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/volunteers_db:latest

      - name: Start MySQL container
        run: docker run -d -p 3306:3306 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/volunteers_db:latest

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install NPM Dependencies
        run: npm install

      - name: create ENV file
        run: cp .sample-env .env

      - name: Run integration tests
        run: npm run test:integration # Replace this with your test command

